version: '3'

services:
 guest-server:
  image: nginx
  container_name: 'guest-container'
  volumes:
   - ./guest-server:/usr/share/nginx/html
  ports:
   - 7000:80

 user-server:
   image: nginx
   container_name: 'user-container'
   volumes:
    - ./user-server:/usr/share/nginx/html
   ports:
    - 7001:80

 reverse-proxy:
  image: nginx
  volumes:
   - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
  ports:
   - 80:80